#!/bin/bash
#PROGRAMM FILE: exit_code
#PROGRAMMER: Rolan Abbasguliev

isnum()
{
  #re='^[0-9]+$'
  if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then 
    return 0
  else
    return 1
  fi
}

exit_code() 
{  
 if ! $(isnum $1); then
   echo -e "${RED}EXIT CODE IS NOT A NUMBER${NC}" 1>&2
   return -1
 fi 
 if [ -z "$1" ]
 then  
   echo "exit code: 0"
   exit 0
 else
   echo "exit code: $1"
   exit $param2
  fi 
}


