#!/bin/bash
#PROGRAMM FILE: MyScript
#PROGRAMMER: Abbasguliev Rolan

source script_load
script_load
 
call_func=$1
param2=$2
 case $call_func in
  calc)
    clear
    calc "$2" "$3" "$4"
    ;;
  search)
    clear
    search "$2" "$3"
    ;;
  reverse)
    clear
    reverse "$2" "$3"
    ;;
  strlen)
    clear
    strlen "$2" 
    ;;
  log) 
    clear
    log
    ;;
  exit)
    clear
    exit_code "$2"
    ;;
  help)
    clear
    help 
    ;; 
  interactive) 
    clear
    interactive
    ;; 
  *)
    clear
    help
    echo -e "${RED} YOU TYPED FUNCTION DOESN'T EXIST ${NC}" 1>&2
    ;;
esac

