#!/bin/bash
#PROGRAMM FILE: reverse
#PROGRAMMER: Abbasguliev Rolan

source MyColor
reverse()
{
  local file_f=$1
  local file_s=$2
  [ -f "$file_f" ]

  if [[ $? != 0 ]]; then
    echo -e "${RED}No Such file: $file_f${NC}"
    exit -1
  fi

  [ -f "$file_s" ]

  if [[ $? != 0 ]]; then
    echo -e "${RED}No Such file: $file_s ${NC}"
    exit -1
  fi
 
  echo -e "${GREEN}Append or Rewrite ? [a/r]${NC}"
  read -r ch
  case $ch in 
    a) tac $file_f >> $file_s ;;
    r) tac $file_f > $file_s ;;
    *) echo -e "${RED}You have no choice${NC}" ;;
  esac
}

