#!/bin/bash
#PROGRAMM FILE: script_load
#PROGRAMMER: Rolan Abbasguliev

declare -ga array_func=("MyColor" "calc" "search" "reverse" "strlen" "log" "helpme" "exit_code" "interactive") 

script_load()
{
  for var in "${array_func[@]}"
  do 
    source $var 
    if (( $? == 0 )); then
      echo -e "${GREEN}$var script loaded !${NC}"
      sleep 0.05
    else
      for (( i=0; i < 9; i++))
      do 
        array_func[i]="load_error" 
        break
      done
      echo -e "${RED}$var script error !${NC}" 1>&2
    fi
  done 
}


