#!/bin/bash
#PROGRAMM FILE: search
#PROGRAMMER: Rolan Abbasguliev
source MyColor 
search() 
{

  local file_name=$1
  local pattern=$2
#  if  test -f $file_name; then
#    true
#  else 
#    echo -e "${RED}No such file: $file_name${NC}" 1>&2
#    return -5
#  fi
  grep -r $pattern /$file_name 
}


